import { Inter } from "next/font/google";
import { getServerSession } from 'next-auth';
import SessionProvider from './components/SessionProvider';
import { Navbar } from './ui/navbar';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} min-h-screen bg-[radial-gradient(circle_at_top_left,_#f1f5f930,_transparent_60%)] dark:bg-[radial-gradient(circle_at_top_left,_#1e293b60,_transparent_60%)] text-gray-900 dark:text-gray-100 antialiased`}>        
        <SessionProvider session={session}>
          <Navbar />
          <main className="max-w-5xl mx-auto px-4 md:px-6 py-10">
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}